"""Prepare the complete referee disposition matrix; no blanket closure flags."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
out=ROOT/'revisions/2026-09-24-r29/disposition.json'
rows=[]
def add(prefix,kind,entries):
    for n,issue,answer,evidence,status in entries:
        rows.append(dict(id=f'{prefix}-{kind}{n}',issue=issue,response=answer,evidence=evidence,status=status))
A='Article; SUPP_R29; COMPUTATION_R29; HISTORY_R29; REVISION_MANIFEST.json'
B='Article: residual envelopes and state-dependent budgets; controls.py; results/controls'
C='Article: constrained polling and stopped slice; R28 results/slice_summary.json'
D='Article: recentered historical transport; R28 results/central/mechanism_summary.json'
E='Article: synchronous deployment; R28 results/central/production_summary.json'
F='Article: original economic target and conclusion; R25 results/full_state/summary.json'
G='COMPUTATION_R29: cost and resource ledgers; results/controls; controls_cli_resource.txt'
H='Article: literature positioning; paper/references.tex'
I='PROTOCOL.md; PROTOCOL_AMENDMENT_01.md; per-model FREEZE_MANIFEST.json and events.json'
J='test_revision.py; source_audit/PRESERVATION.json; exact-commit validation artifact'
K='Article: scaling and robustness; SUPP_R29: tolerance panel; COMPUTATION_R29: all candidates'
L='REVISION_INDEX.md; disposition.json; archived referee reports'
closed='Correction implemented with the specified evidence.'
partial='The stated extension is established; the broader original scientific requirement remains unestablished.'
open_='Original requirement retained and explicitly not claimed as established.'
add('R27','F',[
(1,'Materialized referee object','The revision now contains a complete article, essential supplement, computational appendix, response, and historical annex, with source, frozen results, tests, and reproduction instructions. The previous design-only snapshot is not described as a completed manuscript. The current index identifies R29 and the exact reports addressed.',A,closed),
(2,'Missing original raw R27 artifacts','The absent R27 raw-run files are not silently reconstructed or assigned retrospective hashes. The existing R28 run is identified by its source and evidence commits. All 34 of its raw policy files are preserved, and the new 81 candidates have their own training records, hashes, dependency audit, and freeze events before reference generation. This supplies a new auditable record, not proof of the missing historical chronology.',I+'; R28 frozen inventory records','New evidence supplied; missing historical R27 record not retroactively established.'),
(3,'Executable exact-head validation','The new validation workflow runs on every push to the new revision branch without a commit-message gate. It checks the frozen data and source identities from a clean checkout, rebuilds every current PDF, and retains the checked SHA and run identity in an external artifact. The separate expensive scientific-generation workflow is not confused with final-head validation.',J,closed),
(4,'Generic repair versus neural contribution','Both repair rules are applied to neural, polynomial, ten-seed random-feasible, myopic, base-stock, and two-period tabular proposals. Raw regret, raw residual bounds, correction counts, suffix deficits, topology, and full stage costs are reported separately. The theorem is representation independent. Any neural benefit must be visible in the paired raw quality or burden comparison, rather than inferred from a completed certificate.',B+'; SUPP_R29: attribution table',closed),
(5,'Post-diagnostic status','The R27 completion amendment remains identified as post-diagnostic. R28 and R29 are later executions, and the new state-dependent budget rule and expanded controls are exploratory relative to prior outcomes. A committed cohort and programmatic reference isolation are useful reproducibility controls, but they are not described as investigator blinding or retroactive preregistration.',I,closed),
(6,'Small unknown-solution benchmark','The unchanged original four models are retained and the fixed cohort adds dimensions five, six, and seven, reaching 16,384 states per slice. The study measures both approximation and exact-enumeration costs. These larger finite graphs are a scaling diagnostic, not evidence that neural approximation is necessary or that continuous high-dimensional control has been solved.',K,partial),
(7,'Tabular certification complexity','The paper states feasible and dense state-action-successor counts, O(TNAD) arithmetic enumeration, exact-integer bit growth, and model/policy storage. Exact dynamic programming remains visible in the main scaling table. A complete action-table audit is not claimed to evade the curse of dimensionality.',B+'; '+G,closed),
(8,'Raw four-dimensional failure','The raw neural policies, including the previously reported loss near 0.36656, are preserved. The complete ledger distinguishes raw loss, raw bound, each completed bound, and edited actions for every policy. Fitting, completion, verification, and exact reference costs are separate. The raw failure is neither removed nor relabeled as neural success after repair.',K+'; '+G,closed),
(9,'Constrained stationarity','The article states the projected-gradient mapping, a precision-aware finite-work theorem on a closed box, the short-face alternative, and explicit unresolved-oracle semantics. Its assumptions are instantiated in two original-economy slices at four meshes with measured oracle calls, validated derivative bounds, and boundary or interior optima.',C,closed),
(10,'Scalar slice versus original policy class','The fixed consumption, zero risky investment, constant preference-adjustment interval, initial state, and two cost coefficients are stated explicitly. The class regret certificate is not substituted for the financed 47-dimensional class or for all states and restarts of the original economy. The economic comparative-static content is retained without changing the original target.',C+'; '+F,closed),
(11,'Stopped derivative bridge','A change-of-path-measure argument gives value, first-derivative, and second-derivative stopping-error bounds for the scalar class, including the explicit parameter dependence of the quadratic cost. Analytic Gaussian-tail and polynomial remainders are enclosed with directed arithmetic. The general financed 47-dimensional derivative-error constants are still not instantiated; finite secants are not presented as that bridge.',C+'; Article: financing-gradient formula',partial),
(12,'Historical-transport isolation','The six executed paths independently implement direct neural differentiation and quotient-gradient pullback with the same carrier, Adam state, and full nonlinear recentering. Every nonlinear remainder is retained and there is no unmatched displacement cap. Parameter, output, moment, and displacement diagnostics are included. This is a path-equivalence experiment, not a cheaper carrier-free optimizer.',D,closed),
(13,'Production rollback','The fixed production-schedule study contains twelve gated and ungated trajectories, matched by seed and optimizer, including direct L-BFGS-B. Every checkpoint interval, strict comparison, rejection/restoration record, gradient count, and component timing is retained. The paired final-payoff interval determines whether an improvement is actually proved; restoration correctness alone is not called solver superiority.',E,closed),
(14,'Original whole-domain target','The original current-state, all-state, all-restart tolerance remains 0.01. The inherited bound is 7.181834580823298. The revision develops constructive finite-state and scalar stopped-control guarantees but does not claim that they close this original quantitative requirement. Neither the title nor the original economy is replaced by the auxiliary model.',F,open_),
(15,'Stale review lineage','The index now names R29, the R27 report and exact review head, and the R26 and R25 second-pass crosswalks. The previous index is archived byte-for-byte. The missing review files on the R28 base are carried into the new branch as their original Git blobs rather than rewritten summaries.',L,closed),
(16,'Literature and novelty','The positioning distinguishes fitted-value-iteration error analysis, constrained generating-set search, verified arithmetic, information relaxation, neural stochastic control, and computational economics. The additions are identified as an explicit residual-budget preservation operator, an interval-oracle boundary theorem with stated work, a stopped scalar oracle, and independently executed mechanism controls. The paper does not claim to invent Bellman comparison, policy iteration, direct search, or interval arithmetic.',H,closed),
(17,'Robustness beyond two seeds','The width-32, depth-two panel has ten seeds at the four-dimensional L=4 model and five at L=5; the original architecture controls remain. Ten random policies per original model, larger dimensions, and a paired three-tolerance panel are added under fixed rules. This is structured computational coverage, not a complete robustness theorem over all charts, optimizers, or economies.',K,partial),
(18,'Certified deployment object','The deployed finite-state object is the exact compiled action table after any replacements. The raw neural network remains the proposal object. An unchanged neural execution certificate would need separate floating-point execution analysis, which is not asserted. Each raw and completed policy has its own hash and edit record.',B+'; per-policy action tables',closed)])
add('R27','T',[
(1,'Residual identity and performance bound','The article defines the policy value, nonnegative local Bellman deficit, and state-sensitive residual envelope. A backward proof covers terminal payoff, settlement, feasible actions, time dependence, and every restart. The new budget theorem additionally proves pointwise improvement over the original candidate and nonnegative remaining allowances.',B,closed),
(2,'Information available to completion','Completion uses the full transition law, exact rewards, exact completed-suffix values, all feasible actions, and exact arithmetic. All of these are stated as powerful model resources also available to exact dynamic programming. Absence of an optimal-value file is not equated with a weaker computational oracle.',B+'; main scaling table',closed),
(3,'Trivial-policy controls','Random-feasible, myopic, base-stock, and two-period tabular policies are executed under both identical completion rules. The results retain all seeds and failures and report correction burden and costs alongside neural and polynomial proposals.',K,closed),
(4,'Correction topology','Every changed action records time, state index, original and replacement action, exact suffix deficit, and local allowance. Aggregations distinguish total inventory, minimum inventory, and number of empty coordinates. Restart-specific worst losses and near-default edit counts are reported in the computational appendix.',B+'; COMPUTATION_R29: topology',closed),
(5,'Exact arithmetic cost','The implementation records arbitrary-precision integer and Fraction backends, logical and dense successor counts, value/denominator bit lengths, wall time, CPU time, model arrays, policy bytes, and scoped process high-water memory. It does not call cumulative RSS an isolated per-case peak. Inherited dual setup time is still marked unmeasured.',G,partial),
(6,'Remaining-horizon tolerance allocation','The original fixed eta rule is retained unchanged as a control. The new theorem propagates the already completed suffix envelope and allocates the remaining state-dependent budget, with all-state/all-restart accuracy and policy-preservation proofs. Both rules are evaluated at 0.001, 0.01, and 0.05 on the same tolerance cohort.',B+'; SUPP_R29: tolerance panel',closed),
(7,'Separate numerical stages','The paper separates candidate generation and compilation, raw audit, completion, completed certification, exact reference, and gap comparison. Full model and reference work are charged to non-amortized component sums. Startup and serialization remain visible at cohort level and are not assigned artificial per-method estimates.',G,closed),
(8,'Programmatic reference isolation','The runtime audit rejects optimal-reference reads during candidate generation and completion, and the independent full-horizon solver is disabled in that context. Candidate, variant, and model-freeze hashes precede reference-creation events. Validation checks these events and file identities. This does not establish recovery of the missing R27 chronology.',I+'; controls.py; test_revision.py',closed),
(9,'Strongest classical baseline','Exact scalar backward induction is in the article scaling table, with model construction and solve times retained. Direct L-BFGS-B remains in the continuous production and historical comparisons. Neither is hidden in an appendix to imply a neural advantage.',G+'; '+E,closed),
(10,'Finite versus continuous certification','The finite-state theorem enumerates a graph; the original continuous problem requires domain coverage, derivative or residual enclosures, and a stopped-control comparison. The paper states these as separate complexity regimes. The largest finite graph is not claimed to establish continuous-domain verifier scaling.',B+'; '+F,closed)])
r27n=[(1,'Complete referee copy',1),(2,'Immutable raw evidence',2),(3,'R26 and R25 crosswalk',15),(4,'Attribution-proof completion',4),(5,'Complete completion proof',9),(6,'Executed constrained stationarity',9),(7,'Executed faithful transport',12),(8,'Paired production rollback',13),(9,'Standalone cost ledger',7),(10,'Scaling evidence',6),(11,'Primary-source positioning',16),(12,'Current lineage',15),(13,'Exact-head CI',3)]
for n,issue,f in r27n:
    src=next(x for x in rows if x['id']==f'R27-F{f}')
    ans=src['response'];ev=src['evidence'];status=src['status']
    if n==5:ans=next(x for x in rows if x['id']=='R27-T1')['response'];ev=B;status=closed
    if n==9:ans=next(x for x in rows if x['id']=='R27-T7')['response']+' The earlier central dual-construction cost is not recoverable from its timing records and remains unmeasured.';ev=G;status=partial
    rows.append(dict(id=f'R27-N{n}',issue=issue,response=ans,evidence=ev,status=status))
add('R26','F',[
(1,'Latest-review mismatch','The response identifies the actual R27 report as latest and includes a complete item-by-item R26 and R25 second-pass matrix. The original reports are preserved, not replaced by the stale R24 citation. The revision index and manifest now agree.',L,closed),
(2,'Original 718-fold gap','The original 0.01 target is unchanged, and the retained all-domain bound remains 7.181834580823298. The new finite-state and scalar-class proofs are separate results. No table, abstract, or test flag reports the original target as closed.',F,open_),
(3,'No demonstrated neural advantage','The strongest exact tabular and direct L-BFGS-B comparators remain in the main text. Raw neural success, repair burden, and total costs are reported separately. The neural representation is not credited with a generic exact-model repair outcome, and numerical superiority is not inferred from feasibility.',B+'; '+G,closed),
(4,'Conditional precision complexity','The full work expression includes the interval-oracle factor W(kappa h^2). The derivative and payoff oracle is instantiated at the four executed mesh levels of the stopped scalar class. The theorem does not assert arbitrary precision of the 47-dimensional checker or a bare epsilon-inverse-square total-work result.',C,partial),
(5,'Boundary exclusion','The projected-gradient theorem includes feasible full coordinate steps and geometric short-face cases at closed-box boundaries. Oracle failure is distinct from an infeasible step. Both a binding upper-face optimum and an interior optimum are executed in the original-economy scalar class.',C,closed),
(6,'Stopped gradient','The scalar likelihood-ratio bridge is proved and instantiated with directed analytic remainder budgets, including explicit cost derivatives. The financing-gradient formula retains all approximation and root-shift terms. Its general 47-dimensional constants remain uninstantiated.',C+'; Article: financing-gradient formula',partial),
(7,'Confounded historical transport','The new independent control recenters to the full nonlinear carrier output after each step, retains the complete remainder, and removes the unmatched output cap. Six paths report parameter, quotient, and moment agreement. The old capped/drifting runs remain archived and are not reinterpreted as faithful controls.',D,closed),
(8,'Post-diagnostic stress versus production','The inherited rate-20.48 stress experiment remains historical engineering evidence. The later production study fixes rates and paired gated/ungated rules before that study, retains all checkpoints, and reports interval comparisons of final payoffs. It is not relabeled as the original R25 held-out test.',E,closed),
(9,'Known-solution manufactured example','The manufactured problem is retained as a verifier stress test with its known-witness information stated. The unknown-solution inventory cohort trains only on model primitives and its own approximate suffix values, then freezes policies before a separately generated exact reference.',B+'; '+I,closed),
(10,'High-dimensional verification scaling','The new finite graphs reach dimension seven and 16,384 states and record enumeration, memory, and bit growth. This broadens finite-state coverage. It does not supply a high-dimensional continuous Hessian/interval-cover complexity theorem, which remains a distinct requirement.',K,partial),
(11,'From-scratch cost','Model construction, proposal generation, compilation, completion, certification, and independent reference are separately recorded for the new inventory executions. Non-amortized totals and resource scope are explicit. The old central dual-construction timing is not invented or inferred from later checker times.',G,partial),
(12,'Parameterization robustness','The expanded seed and architecture cohorts, trivial controls, state sizes, and tolerance panels are all retained. The central production study also compares neural and direct optimizers under matched gates. This is wider deterministic coverage, not proof of robustness to every parameter chart or training rule.',K+'; '+E,partial),
(13,'Sparse literature','The article retains the expanded primary bibliography and adds direct-search stationarity comparisons. Each numerical ingredient is attributed to its established literature, and the contribution statement identifies the added oracle, budget rule, coupling result, and application rather than a generic claim of invention.',H,closed),
(14,'Bound-improvement decomposition','The same-cover warm-start and retained-actor bounds, the separate cover refinement, and the all-restart suffix proof remain in the article and historical annex. A tighter bound is not asserted to prove higher original-domain payoff. Only a strict payoff interval comparison or the finite-model preservation theorem supplies that different conclusion.',F+'; Article: all-restart suffix envelope',closed)])
add('R26','T',[
(1,'Full oracle work','The work theorem displays W(kappa h^2) and reports actual oracle work at executed precisions. No headline substitutes an iteration count for total verified work.',C,closed),
(2,'Oracle failure semantics','A feasible point with unresolved verification cannot complete a stationarity poll. The algorithm and theorem distinguish this event from an infeasible full step at a nearby face.',C,closed),
(3,'Exact coefficients versus execution','Rational policy-table certificates and directed coefficient enclosures are distinguished from floating-point network execution. The repaired finite-state table is the deployed object.',B,closed),
(4,'Structurally advantaged comparator','The manufactured reference remains labeled as known-solution and its direct comparator as structurally informed. The independent unknown-solution experiment is separate; neither universal neural inferiority nor superiority is inferred from the manufactured case.',B+'; historical annex',closed),
(5,'Tests versus theorem hypotheses','Validation checks executable identities, hashes, fixed cohorts, and recorded numerical enclosures. The manuscript explicitly states that passing these checks does not establish hypotheses that have not been analytically or numerically instantiated.',J+'; '+C,closed),
(6,'Trajectory distributions','The transport ledger retains every step and reports displacement distribution, nonlinear remainder, moment mismatch, and carrier alignment. The production ledger retains every candidate interval and deployment decision.',D+'; '+E,closed),
(7,'Distinct guarantees','The paper distinguishes monotone deployed payoff, constrained stationarity, finite-state epsilon optimality, and Adam convergence. Only the corresponding proved guarantee is asserted for each operator.',B+'; '+C+'; '+E,closed),
(8,'Economic content','The unchanged stopped economy links costly preference adjustment to a binding boundary at low adjustment cost and an interior solution at the higher cost. This is a verified comparative-static result within the stated class; broader optimal-policy implications are not inferred.',C,closed)])
r26requests=[(1,'R25 second-pass disposition',1),(2,'Original quantitative target',2),(3,'Unknown-solution stochastic control',9),(4,'Instantiate meaningful original-economy control',4),(5,'Boundary-aware proof',5),(6,'Faithful mechanism isolation',7),(7,'Production rollback regime',8),(8,'Dimension and tolerance scaling',10),(9,'All infrastructure cost',11),(10,'Primary literature',13),(11,'Bound decomposition',14),(12,'Title and claim alignment',3)]
for n,issue,f in r26requests:
    x=next(z for z in rows if z['id']==f'R26-F{f}')
    answer=x['response']
    if n==12:answer='The title Neural Bellman Operators is retained, as are the original economic problem and quantitative target. The abstract and theorem statements identify actual neural-proposal, certified-completion, and continuous-control contributions, rather than replacing the project by a weaker problem or asserting an unsupported neural speedup.'
    rows.append(dict(id=f'R26-N{n}',issue=issue,response=answer,evidence=x['evidence'],status=x['status']))
spmap=[(1,'Integrated manuscript','R27-F1'),(2,'Original whole-domain accuracy','R27-F14'),(3,'Held-out frontier','R26-F3'),(4,'Faithful moving transport','R26-F7'),(5,'Cap-driven nominal learning rates','R26-T6'),(6,'Known-witness stochastic benchmark','R26-F9'),(7,'Stopped objective gradient','R27-F11'),(8,'Rollback exercised','R27-F13'),(9,'Certificate versus payoff improvement','R26-F14'),(10,'Dominant verification and full costs','R26-F11'),(11,'Robustness coverage','R27-F17'),(12,'Performance and convergence theorem','R27-F14')]
for n,issue,source in spmap:
    x=next(z for z in rows if z['id']==source);answer=x['response']
    if n==5:answer='The old nominal-rate tuning is retained as a result for the capped algorithm, not clean identification of uncapped learning-rate effects. The new recentered transport experiment has no unmatched cap and reports the complete effective output-step distribution, nonlinear remainder, and moment discrepancies. It does not retroactively change the earlier tuning outcome.'
    if n==12:answer='The article now supplies complete all-state/all-restart finite-state performance theorems, a projected-stationarity theorem with explicit precision-dependent work, and a rigorously instantiated scalar original-economy oracle. These are constructive guarantees. They do not constitute an epsilon-accurate convergence theorem for the original full continuous-state neural iteration.'
    rows.append(dict(id=f'R25-SP-F{n}',issue=issue,response=answer,evidence=x['evidence'],status=x['status']))
sptech=[(1,'Current revision index','R27-F15'),(2,'Preserve chronology','R27-F5'),(3,'Effective output-step statistics','R26-T6'),(4,'Carrier recentering','R27-F12'),(5,'Known-structure comparator','R26-T4'),(6,'All-restart suffix proof','R26-F14'),(7,'Deployment versus regret-bound gate','R26-T7'),(8,'No pseudo-replication','R27-F17')]
for n,issue,source in sptech:
    x=next(z for z in rows if z['id']==source);answer=x['response']
    if n==8:answer='Seeds, architectures, dimensions, repeated tolerance checks, time slabs, and verification cells are reported as computational coverage. They are not pooled as independent observations of one statistical treatment effect. Paired repairs and gated/ungated paths retain their dependence explicitly.'
    rows.append(dict(id=f'R25-SP-T{n}',issue=issue,response=answer,evidence=x['evidence'],status=closed if n==8 else x['status']))
spn=[(1,'Materialize and seal referee object','R27-F1'),(2,'Original orders-of-magnitude progress','R27-F14'),(3,'Faithful neural geometry','R27-F12'),(4,'Proposal-gradient bridge','R27-F11'),(5,'Unknown-solution stochastic benchmark','R26-F9'),(6,'Natural production rejection','R27-F13'),(7,'Broader robustness and scaling','R27-F17')]
for n,issue,source in spn:
    x=next(z for z in rows if z['id']==source)
    rows.append(dict(id=f'R25-SP-N{n}',issue=issue,response=x['response'],evidence=x['evidence'],status=x['status']))
assert len(rows)==102 and len({x['id'] for x in rows})==102
out.write_text(json.dumps(rows,indent=2)+'\n')
print(len(rows),out.stat().st_size)
