"""Idempotently assemble R6 from byte-preserved R2; never edit another branch."""
from pathlib import Path
import hashlib,json,re,shutil
ROOT=Path(__file__).resolve().parents[3];P=ROOT/'revisions/2026-09-29-r6';A=P/'archive';A.mkdir(exist_ok=True,parents=True)
OLD_MAIN='d3261aaa857ce9bdc1c479cc3785711846a3f845';OLD_SUPP='4e8f07484059e1a3d065717bf4d72120fad0c238'
def gitblob(data):return hashlib.sha1(b'blob '+str(len(data)).encode()+b'\0'+data).hexdigest()
for name,target,expected in [('ECTA.tex','ECTA.R2.tex',OLD_MAIN),('supp.tex','supp.R2.tex',OLD_SUPP)]:
 dest=A/target
 if not dest.exists():
  data=(ROOT/name).read_bytes()
  if gitblob(data)!=expected:raise ValueError('unrecognized base source: '+name)
  dest.write_bytes(data)
 if gitblob(dest.read_bytes())!=expected:raise ValueError('archive identity mismatch: '+target)
s=(A/'ECTA.R2.tex').read_text();changes=[]
def paragraph(prefix,text):
 global s
 p=s.split('\n\n');matches=[i for i,x in enumerate(p) if x.startswith(prefix)]
 if len(matches)!=1:raise ValueError('ambiguous paragraph: '+prefix)
 old=p[matches[0]]
 suffix=old[old.index('\n\\end{appendix}'): ] if '\n\\end{appendix}' in old else ''
 p[matches[0]]=text+suffix;s='\n\n'.join(p);changes.append(prefix)
def insert_before(marker,filename):
 global s
 if s.count(marker)!=1:raise ValueError('ambiguous insertion: '+marker)
 s=s.replace(marker,'\\input{revisions/2026-09-29-r6/manuscript/'+filename+'}\n\n'+marker)
abstract='We develop Neural Bellman Operators for continuous-time economic control with recursive utility, constraints, and endogenous preferences. The computation separates policy evaluation from feasible improvement and returns an economic error account. Verification bounds translate evaluation, action, and boundary errors into value and welfare bounds; a positive-weight implementation supplies viscosity selection. We train multilayer critics and actors on a nonhomothetic consumption problem and compute full-domain interval certificates, independently of reference-grid error. Matched direct-HJB and joint-loss comparisons identify both successful solves and consequential optimization failures. Further computations train neural preference-adjustment policies, test dense nonquadratic capital economies and stochastic diffusion traces, and solve finite dynamic Cournot games with independent best responses. Action-domain sensitivity and out-of-domain payoff diagnostics reveal which conclusions transfer beyond a numerical approximation. The framework retains separate criteria for economic optimality, equilibrium deviations, and numerical stationarity.'
s=re.sub(r'\\begin\{abstract\}.*?\\end\{abstract\}',lambda m:'\\begin{abstract}\n'+abstract+'\n\\end{abstract}',s,flags=re.S)
paragraph('The paper makes three contributions.',r'The paper makes three contributions. First, it specifies a neural evaluation--improvement map whose derivative graph, feasible action class, economic boundary data, and verification output are explicit. Second, it connects differential and positive-weight implementations through economic error accounts, including a computable continuous-domain certificate for a trained nonlinear consumption problem. Third, it implements this distinction across endogenous preferences, coupled capital economies, and strategic agents, while retaining recursive utility and temporal selves within the same economic formulation. The numerical comparisons identify approximation costs and failures rather than attributing optimality to parameter stationarity. Monotonicity, comparison, and approximate policy iteration are inherited mathematical ingredients; the implemented economic specification and verified numerical chain are the objects studied here.')
paragraph('The numerical laboratories serve different purposes.',r'The numerical program now includes generic multilayer neural fits as well as the analytical laboratories. A stopped consumption economy has independent upwind references and full continuous-domain neural certificates. Preference adjustment has a same-model neural--Bellman comparison and an action-domain sensitivity study. Dense nonlinear capital models exercise automatic differentiation, stochastic trace estimation, and state coverage. Dynamic Cournot profiles receive independent fixed-rival best-response calculations. Homothetic portfolios, temporal-self formulas, the nonsmooth exit problem, and the exact coupled quadratic family remain as distinct economic and algebraic checks. No analytical or matrix calculation is counted as a generic neural training run.')
paragraph('Section~\\ref{sec:model} specifies',r'Section~\ref{sec:model} specifies the economy. Section~\ref{sec:method} defines the implemented map and Section~\ref{sec:theory} establishes its error accounts. Section~\ref{sec:nonquadratic} completes the differential theorem--algorithm--experiment chain. The subsequent sections retain and extend the portfolio, recursive-utility, preference-adjustment, temporal-self, dynamic-game, and scaling applications. The appendix proves the principal results. The supplement gives arithmetic details, application-specific assumptions, every seed-level comparison, and sensitivity results.')
insert_before(r'\section{Verification, Approximation, and Viscosity Selection}','operator.tex')
insert_before(r'\section{Analytical and Nonsmooth Benchmarks}','bridge.tex')
insert_before(r'\section{Analytical and Nonsmooth Benchmarks}','consumption.tex')
paragraph('At $(u,X)=(2.1,1)$,',r'At $(u,X)=(2.1,1)$, the original $17\times25$ state grid and 20 time steps give values $-11.915211$ and $-11.956983$ for $k=1$ and $k=5$. The $25\times37$ grid and 40 time steps give $-11.866768$ and $-11.908738$. Both select $(c/X,p,\theta)=(.1,.75,-.15)$ at that point. The approximately $.048$ refinement change is reported separately from training error. The higher-cost value is weakly lower at every recorded node and time. These original references remain useful consistency checks; Section~\ref{sec:ndu-neural} supplies actual neural fits and shows how strongly the finite action domain affects their economic comparison.')
insert_before(r'\section{Sophisticated Temporal Selves}','ndu.tex')
s=s.replace(r'\subsection{Symmetry, market scaling, and the remaining numerical comparison}',r'\subsection{Symmetry and market scaling}')
paragraph('Under fixed market size,',r'Under fixed market size, positive constant capital per firm cannot be called the competitive limit while total output tends to infinity and the truncated price tends to zero. Maintaining that capital entails investment and adjustment costs. Under $M_N=N$, positive capital per firm may instead be compatible with a growing market, but it describes a different sequence of economies. The original unsupported capital table remains in the archive. Section~\ref{sec:dynamic-computation} replaces its evidentiary role with a fully specified finite dynamic game and independent best-response calculations, without asserting convergence of unrestricted neural game training.')
insert_before(r'\section{Scalability and the Diffusion Trace}','games.tex')
insert_before(r'\subsection{Exact and stochastic trace computation}','coupled.tex')
insert_before(r'\section{Conclusion}','trace.tex')
paragraph('The executed laboratories establish',r'The computations now connect a genuinely trained multilayer NBO to a continuous-domain economic certificate, compare it with an architecture-matched direct neural HJB solve, and retain a failed joint-loss ablation. Neural preference adjustment, dense nonquadratic capital models, actual trace-estimator training, and dynamic fixed-rival best responses extend the same program beyond exactly representable calibrations. Their error accounts remain distinct: a finite-game equilibrium is not a continuous-game theorem, and sampled high-dimensional residuals do not certify policy payoffs outside their verification region. This separation permits substantive computational progress without changing the economic agenda or treating numerical convenience as an optimality argument.')
paragraph('The primary execution contains 29 recorded experiments:',r'The inherited R2 execution contains 29 recorded experiments and eight regression tests, all retained and rerun. The R6 record adds nine primary stopped-consumption runs, six architecture/update sensitivities, six full-domain certificates, six principal NDU neural runs, sixteen NDU reference sensitivities, twenty-four dense-capital primary fits, six stochastic-trace fits, twelve coverage follow-ups, and six principal dynamic-game solves. Pilot failures and coarse-game counterchecks are retained separately rather than counted as successful primary runs. The original referee diagnostics continue to concern their pinned original sources.')
paragraph('No claim is made here of a reproduced historical',r'The R6 directory contains complete source, generated tables, model and numerical arrays, optimizer histories, certificate covers, tests, and a provenance manifest. The replication workflow materializes the revision source, independently reruns its computations, and commits the resulting evidence only to the designated R6 candidate branch; an exact-source snapshot and raw-result hashes identify each execution. Local execution, remote replication, and independent referee acceptance remain different facts. No historical GPU benchmark, unexecuted deep-BSDE comparison, unrestricted neural Cournot equilibrium, or empirical identification result is inferred from the computations reported here.')
(ROOT/'ECTA.tex').write_text(s)
u=(A/'supp.R2.tex').read_text()
u=u.replace('The numerical laboratories have explicit approximation classes. The portfolio calibration uses homothetic output parameters; the coupled quadratic calculation uses a quadratic neural critic with exact policy evaluation; and the NDU calculation is an independent grid reference. The general differential core supports smooth batch-separable multilayer networks. Its gradient-routing tests are not presented as evidence that such a network was trained on every application. This distinction is important when reproducing the numerical results.', 'The inherited portfolio and quadratic laboratories retain their declared exact-structure classes. R6 additionally trains generic multilayer actors and critics in a stopped consumption economy, the NDU finite approximation, and dense nonlinear capital economies. The dynamic-game computation is a finite-grid best-response calculation. These approximation classes remain distinct throughout the run-level accounts below.')
u=u.replace('The coupled laboratory is explicitly the former.', 'The inherited quadratic laboratory is explicitly the former; the new dense nonlinear experiments actually train generic networks and Hessian-vector estimators.')
u=u.replace('These are declared comparison requirements; no missing run is represented as a measured advantage in the article.', 'R6 executes the architecture-matched direct-HJB and finite-Bellman comparisons. The broader deep-BSDE and neural-game comparisons remain distinct unexecuted alternatives; they are not counted as measured advantages.')
u=u.replace('The read-only verification workflow rebuilds the experiments and PDFs from its checked-out revision commit and uploads execution artifacts. It does not modify source, rewrite acceptance status, or push results back into the candidate branch. A locally passed test, a remote workflow result, and independent referee acceptance remain separate facts.', 'The inherited read-only workflow is preserved. The separately scoped R6 replication workflow commits materialized source and raw recomputation outputs only to its designated candidate branch, without editing the review or earlier revision branches. Hashes and exact source commits distinguish these artifacts. No workflow rewrites a failed numerical accuracy target as a pass.')
u=u.replace(r'\end{document}',r'\input{revisions/2026-09-29-r6/manuscript/supplement_details.tex}'+'\n'+r'\input{revisions/2026-09-29-r6/manuscript/tables_supplement.tex}'+'\n'+r'\end{document}')
(ROOT/'supp.tex').write_text(u)
(P/'ASSEMBLY.json').write_text(json.dumps(dict(base_main_blob=OLD_MAIN,base_supp_blob=OLD_SUPP,changed_paragraph_prefixes=changes,abstract_words=len(abstract.split()),main_sha256=hashlib.sha256((ROOT/'ECTA.tex').read_bytes()).hexdigest(),supp_sha256=hashlib.sha256((ROOT/'supp.tex').read_bytes()).hexdigest()),indent=2)+'\n')
print('Assembled R6; abstract words:',len(abstract.split()))
