"""Present-revision additions to all eighteen retained referee answers."""
ADDITIONS={
'B1':r'''The independent assessment now measures the fitted scalar object's risk directly, without replacing its nonlinear fit by a fixed dictionary. Section~\ref{sec:r18risk} reports all 24 conditional comparisons: eight favor NBO by the prespecified risk margin, four favor Raw, and twelve remain unresolved. Section~\ref{sec:r18catalogue} further gives a common accuracy--work comparison across every budget. NBO is the least-cost certified candidate in Intermediate, dimension fifty, with catalogue-regret upper bound $0.000091391$. This is additional economic evidence for the NBO-centered paper. It is not a claim that risk ordering alone proves payoff superiority or that an uncertified cheaper candidate is inaccurate.''',
'B2':r'''The current main article keeps the strengthened-HJB comparison and its independent selection diagnostics unchanged. The new continuation-risk and catalogue results do not use HJB's poor performance to identify NBO's contribution: they compare the common continuation with cached Raw and the complete five-method budget catalogue, respectively. No unsupported HJB-class superiority claim is introduced.''',
'B3':r'''Section~\ref{app:r18record} now gives a single chronology for the old analytical refinement, the later prospective confirmation, the independently frozen contrast-risk assessment, and the present catalogue closure. The last is explicitly a post-freeze reanalysis. Its confidence argument is the simultaneous-event theorem, not an assertion of prospective registration.''',
'B4':r'''The contrast-risk table retains every calibration, dimension, and Raw budget, including the Low and Long reversals. The catalogue table similarly reports all eight choices rather than only the favorable Intermediate result. These are complete finite design populations, not inference to an unspecified natural distribution of future training runs.''',
'B5':r'''Proposition~\ref{prop:r18closure} supplies a new sharp lower and upper accuracy account relative to the entire sixteen-candidate vector-decision catalogue. It is stronger than considering only one comparator at the final stage. Six final NBO candidates are certified within $10^{-4}$ of the best catalogue payoff. The target is explicitly distinguished from both the continuous scalar action interval and the full adapted diffusion class. All earlier full-class regret bounds and classical scalar comparisons remain visible; no finite catalogue is relabelled as a global HJB solution.''',
'B6':r'''Corollary~\ref{cor:r18selection} and Table~\ref{tab:r18catalogue} compare every stage under one economic accuracy target. In Intermediate, dimension fifty, NBO is the least-cost member of the certified set, not merely cheaper than final 64-path SAA. The cheaper final Raw and vector actors have regret lower bounds above the target. Cheaper four-path SAA and second-stage NBO remain unresolved. Early-stage costs retain their prefix-allocation status, and Table~\ref{tab:r18bills} reports the full shared assessment and the complete bill for all competing constructions. No retrospective selection is described as saved historical work.''',
'B7':r'''The new noise-cancelled statistic compares continuation contrasts at identical NBO/reference action pairs, with predictions and realized Raw caches fixed before independent assessment. Its variance is proportional to the squared difference between predictions, and no noisy estimate of the common squared true continuation is needed. The complete report replays exactly from the archived observations. Eight intervals establish lower NBO risk, four establish the reverse, and twelve remain unresolved. Proposition~\ref{prop:r17-decisions} states the connection to binary decision loss and also explains why risk ordering does not establish a causal decomposition of policy gains.''',
'B8':r'''The new main sections state the risk object, economic results, and finite-catalogue decision criterion. Their proofs, every candidate record, and full comparison bills are in the technical supplement. The application companion remains a current, cross-referenced scientific document. No historical application, proof, or unfavorable result is deleted to shorten the evidence record.''',
'M1':r'''The single numerical question remains when a learned common continuation improves economic decisions or their accuracy--work account. The new conditional-risk and complete-budget results address that question directly; the paper is not replaced by a candidate-generator-neutral verification topic.''',
'M2':r'''The exact-trace, multi-configuration, independently selected HJB baseline remains the declared comparator. Its full diagnostics and both deployments are preserved. The new conclusions neither generalize this implementation to the whole HJB class nor remove its successful outcomes.''',
'M3':r'''The independent confirmation remains prospective on the original frozen policy population. It is distinct from the new deterministic catalogue selection and from the independent contrast-risk bank. No newly trained-policy claim is attached to an unchanged policy assessment.''',
'M4':r'''The Raw comparison now has three explicitly different objects: Raw-actor economic payoff, cached-Raw contrast risk, and the complete budget catalogue. Learning improves eight conditional risk comparisons and gives the least-cost certified catalogue choice in the fifty-dimensional Intermediate cell. All Raw-favoring intervals, cheaper candidates, and uncertified alternatives are retained. These results justify retaining the learned continuation as the protagonist without asserting universal dominance.''',
'M5':r'''Tables~\ref{tab:r18risk} and~\ref{tab:r18catalogue} report the entire same four-design, two-dimension family. The added analysis gives a map of where risk reduction and certified economic work occur, including their failures to coincide. No new outcome-selected calibration or replacement stream is introduced.''',
'M6':r'''The complete-budget graph produces exact interval-defined regret bounds, with an extremal-potential proof of both upper and lower sharpness. The new high-dimensional accuracy statement concerns computed vector decisions over the same economic population. It does not require an inaccessible full optimum, and it does not identify that catalogue optimum with the continuous or adapted optimum.''',
'M7':r'''The independent risk protocol fixes the coefficient-scaled range, terminal-quadratic centering, tail and arithmetic allowances, sample size, and $10^{-8}$ risk margin before audit draws. Every query receives 256 independent antithetic pairs. Common continuation noise cancels from the difference of squared errors. All 24 risk intervals, including the four reversals and twelve unresolved comparisons, remain in Table~\ref{tab:r18risk}; none is inferred from a training loss.''',
'M8':r'''The abstract and main introduction distinguish conditional risk evidence and catalogue certification from the independent paired confirmation. Section~\ref{app:r18record} explicitly labels the new closure as post-freeze, retaining the old dimension-ten original and refined intervals and their separate chronology.''',
'M9':r'''The original four-document reading structure is retained. New primary objects and two compact tables appear in the article; new complete proofs and all 128 candidate records appear in the supplement. The revised source audit checks inherited labels, mathematical environments, exact previous roots, and unchanged scientific files rather than removing content to meet a page target.''',
'M10':r'''The main text additionally distinguishes conditional risk from payoff, risk difference from absolute risk, realized Raw-cache risk from risk averaged over future caches, catalogue regret from full-class regret, and least certified cost from true minimum work. The risk family uses $.01$; its union with menu payoff uses $.028$, while its union with all previous scientific families uses $.06$. Thus no unearned global $.95$ coverage statement is made. Early-stage prefix allocations and actual complete construction clocks are distinguished in every new work table.'''
}
